language: scala
sbt_args: "-J-Xmx2G"

before_install:
  - git fetch --tags

stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork

jobs:
  include:
    - name: test
      script: sbt clean scripted makeSite
    # run ci-release only if previous stages passed
    - stage: release
      script: sbt ci-release ghpagesPushSite
